version: '2'

services:

  #   see: https://hub.docker.com/r/yinlinchen/fcrepo4-docker/
  #   contains:
  #     Fedora (...:8080/fcrepo)
  #     Apache Karaf, Apache Camel
  fcrepo:
    #build: docker/fcrepo/                    # on linux based hosts
    build:                                    # on mac osx based host
      context: ./docker/fcrepo
      dockerfile: Dockerfile
    working_dir: /usr/local/tomcat
    container_name: gdz-be-$RAILS_ENV-fcrepo
    restart: always
    #command: sleep 6000
    depends_on:
      - fuseki
      - solr
      - redis
    ports:
      - "8444:8080"
      - "9080:9080"
    volumes:
      - $FCREPO_STORAGE/fcrepo/:/var/lib/tomcat/fcrepo4-data  # todo data dir (storage)
    links:
      - redis
      - solr
      - fuseki
    #user: "root"


  # builds the fcrepo repo war, which can be reused from the fcrepo service
  # the idea behind this service is to separate the build and runtime environment
#  fcrepo_build:
#    build: docker/fcrepo_build/
#    container_name: gdz-be-$RAILS_ENV-fcrepo_build
#    command: sleep 360
#    volumes:
#      - ./build/fcrepo/:/fcrepo/
#    environment:
#      FEDORA_VERSION: 4.5.0
#    user: docker:docker


  #   Solr (...:8983/solr)
  #   based on: https://github.com/docker-solr/docker-solr/blob/2e1ccd64970c65e7dacfe33203963b315f665cc3/5.5/Dockerfile
  solr:
    #image: solr:5.5
    build: docker/solr/
    container_name: gdz-be-$RAILS_ENV-solr
    restart: always
    ports:
      - "8443:8983"
    environment:
      SOLR_VERSION: 5.5
      SOLR_HOME: /opt/solr/
      JAVA_OPTS: "-server -Xms512M -Xmx1792M -XX:MaxPermSize=768M"
    volumes:   # todo data dir (storage)
      - $FCREPO_STORAGE/solr/:/opt/solr/gdz/data/


  #   Fuseki (...:3030/fuseki)
  #   admin password will be generated on first start-up (see the logs)
  fuseki:
    image: stain/jena-fuseki
    container_name: gdz-be-$RAILS_ENV-fuseki
    restart: always
    #ports:
    #  - "3030:3030"
    volumes:
      - $FCREPO_STORAGE/fuseki/:/fuseki/ #databases/  # todo data dir (storage)
    user: "1000"


  redis:
    image: redis:3.0
    command: redis-server --appendonly yes
    container_name: gdz-be-$RAILS_ENV-redis
    restart: always
    #ports:
    #  - "6379:6379"
    volumes:
      - $FCREPO_STORAGE/redis/:/data/  # todo data dir (storage)
    user: "1000"

  web:
    #build: docker/web/
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bundle exec passenger start --port 3000
    container_name: gdz-be-$RAILS_ENV-web
    restart: always
    links:
      - redis:redis
      - fcrepo:fcrepo
    volumes:
      - .:/web
    ports:
      - "8442:3000"


  # for optimization start more then one instance of the node running the background processing (via docker swarm or kubernetes)
  gdz-be-worker:
    #build: docker/web/
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bundle exec sidekiq -q mets,8 -q collection,5 -q fileset,5
    # container_name: worker    # you cannot scale a service beyond 1 container if you have specified a custom name (container names must be unique)
    restart: always
    depends_on:
      - web
    links:
      - redis:redis
      - fcrepo:fcrepo
    volumes:
      - .:/web
    #ports:
      #  - "3001"

#  fcrepo4-docker:
#    image: yinlinchen/fcrepo4-docker:4.5.0
#    ports:
#      - "8080:8080"
#      - "9080:9080"
#    volumes:
#      - /Users/jpanzer/tmp/:/usr/local/tomcat7/fcrepo4-data
      #- /tmp/data:/usr/local/tomcat7/fcrepo4-data

#worker_2:
#  build: .
#  command: bundle exec sidekiq -q mets,8 -q collection,5 -q fileset,5
#  container_name: worker_2
#  restart: always
#  links:
#    - redis:redis
#    - fcrepo:fcrepo
#  volumes:
#    - .:/web
#
#worker_3:
#  build: .
#  command: bundle exec sidekiq -q mets,8 -q collection,5 -q fileset,5
#  container_name: worker_3
#  restart: always
#  links:
#    - redis:redis
#    - fcrepo:fcrepo
#  volumes:
#    - .:/web
#
#worker_4:
#  build: .
#  command: bundle exec sidekiq -q mets,8 -q collection,5 -q fileset,5
#  container_name: worker_4
#  restart: always
#  links:
#    - redis:redis
#    - fcrepo:fcrepo
#  volumes:
#    - .:/web
#
#worker_5:
#  build: .
#  command: bundle exec sidekiq -q mets,8 -q collection,5 -q fileset,5
#  container_name: worker_5
#  restart: always
#  links:
#    - redis:redis
#    - fcrepo:fcrepo
#  volumes:
#    - .:/web


#storage:
#  image: busybox
#  volumes:
#    - /var/lib/docker/storage
#  command: true

#haproxy:
#  build: .
#  command: .
#  hostname: active-proxy
#  volumes:
#    - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
#  ports:
#    - "80:80"

#nginx:
#  image: nginx
#  ports: 80:80
