web:
  extends:
    file: compose_default.yml
    service: web
  links:
    - db:db
  environment:
    #- SOLR_ENDPOINT=http://adw-dev.tc.sub.uni-goettingen.de/solr/edfu
    - DOCKER_ENV=development
    - RAILS_ENV=development

db:
  extends:
    file: compose_default.yml
    service: db