development:
  adapter: solr
  url: http://solr:<%= ENV['SOLR_PORT'] || 8983 %>/solr/gdz
test: &test
  adapter: solr
  url: http://solr:<%= ENV['SOLR_PORT'] || 8983 %>/solr/gdz-test
production:
  adapter: solr
  url: http://solr:<%= ENV['SOLR_PORT'] || 8983 %>/solr/gdz-live

