development:
  user: fedora4 # fedoraAdmin
  password: fedora4
  #url: <%= ENV['FCREPO_PORT_8080_TCP_ADDR'] %><%= ENV['FCREPO_PORT_8080_TCP_PORT'] %>/rest
  url: http://fcrepo:8080/fcrepo/rest
  base_path: /dev
test:
  user: fedora4
  password: fedora4
  #url: <%= ENV['FCREPO_PORT_8080_TCP_ADDR'] %><%= ENV['FCREPO_PORT_8080_TCP_PORT'] %>/rest
  url: http://fcrepo:8080/fcrepo/rest
  base_path: /test
production:
  user: fedora4
  password: fedora4
  url: http://127.0.0.1:8080/fedora/rest
  base_path: /prod
