development:
  user: fedora4 # fedoraAdmin
  password: fedora4
  url: http://<%= ENV['FCREPO_DOMAIN'] || '127.0.0.1' %>:<%= ENV['FCREPO_EXTERNAL_PORT'] || 8080 %>/fcrepo/rest
  base_path: /dev
test:
  user: fedora4
  password: fedora4
  url: http://<%= ENV['FCREPO_DOMAIN'] || '127.0.0.1' %>:<%= ENV['FCREPO_EXTERNAL_PORT'] || 8080 %>/fcrepo/rest
  base_path: /test
production:
  user: fedora4
  password: fedora4
  url: <%= ENV['FCREPO_DOMAIN'] || '127.0.0.1' %>:<%= ENV['FCREPO_EXTERNAL_PORT'] || 8080 %>/fedora/rest
  base_path: /live
