# This is a sample config file that points to a solr server for each environment
development:
  url: http://solr:<%= ENV['SOLR_PORT'] || 8983 %>/solr/gdz
test:
  url: http://solr:<%= ENV['SOLR_PORT'] || 8983 %>/solr/gdz-test
production:
  url: http://solr:<%= ENV['SOLR_PORT'] || 8983 %>/solr/gdz-live
