# This is a sample config file that points to a solr server for each environment
development:
  #url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8983 %>/solr/hydra-development
  url: http://fcrepo:8080/solr/hydra-development
test:
  #url: http://127.0.0.1:<%= ENV['SOLR_TEST_PORT'] || 8985 %>/solr/hydra-test
  url: http://fcrepo:8080/solr/hydra-test
production:
  # todo moify this for the production environment
  url: http://your.production.server:8080/bl_solr/core0
